# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easydaq/configurechart.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(467, 202)
        self.gridLayout = QtGui.QGridLayout(MainWindow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 27))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cBposchannel = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBposchannel.sizePolicy().hasHeightForWidth())
        self.cBposchannel.setSizePolicy(sizePolicy)
        self.cBposchannel.setMinimumSize(QtCore.QSize(110, 27))
        self.cBposchannel.setObjectName(_fromUtf8("cBposchannel"))
        self.gridLayout.addWidget(self.cBposchannel, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 27))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.sBrate = QtGui.QSpinBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBrate.sizePolicy().hasHeightForWidth())
        self.sBrate.setSizePolicy(sizePolicy)
        self.sBrate.setMinimumSize(QtCore.QSize(110, 27))
        self.sBrate.setMinimum(1)
        self.sBrate.setMaximum(65536)
        self.sBrate.setProperty("value", 100)
        self.sBrate.setObjectName(_fromUtf8("sBrate"))
        self.gridLayout.addWidget(self.sBrate, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 27))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cBnegchannel = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBnegchannel.sizePolicy().hasHeightForWidth())
        self.cBnegchannel.setSizePolicy(sizePolicy)
        self.cBnegchannel.setMinimumSize(QtCore.QSize(110, 27))
        self.cBnegchannel.setObjectName(_fromUtf8("cBnegchannel"))
        self.gridLayout.addWidget(self.cBnegchannel, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(110, 27))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.sBsamples = QtGui.QSpinBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBsamples.sizePolicy().hasHeightForWidth())
        self.sBsamples.setSizePolicy(sizePolicy)
        self.sBsamples.setMinimumSize(QtCore.QSize(110, 27))
        self.sBsamples.setProperty("value", 20)
        self.sBsamples.setObjectName(_fromUtf8("sBsamples"))
        self.gridLayout.addWidget(self.sBsamples, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.cBrange = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBrange.sizePolicy().hasHeightForWidth())
        self.cBrange.setSizePolicy(sizePolicy)
        self.cBrange.setMinimumSize(QtCore.QSize(110, 27))
        self.cBrange.setObjectName(_fromUtf8("cBrange"))
        self.gridLayout.addWidget(self.cBrange, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 27))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.cBmode = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBmode.sizePolicy().hasHeightForWidth())
        self.cBmode.setSizePolicy(sizePolicy)
        self.cBmode.setMinimumSize(QtCore.QSize(100, 27))
        self.cBmode.setObjectName(_fromUtf8("cBmode"))
        self.cBmode.addItem(_fromUtf8(""))
        self.cBmode.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cBmode, 2, 3, 1, 1)
        self.rBstream = QtGui.QRadioButton(MainWindow)
        self.rBstream.setMaximumSize(QtCore.QSize(120, 30))
        self.rBstream.setChecked(True)
        self.rBstream.setObjectName(_fromUtf8("rBstream"))
        self.gridLayout.addWidget(self.rBstream, 3, 2, 1, 1)
        self.rBextern = QtGui.QRadioButton(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rBextern.sizePolicy().hasHeightForWidth())
        self.rBextern.setSizePolicy(sizePolicy)
        self.rBextern.setMinimumSize(QtCore.QSize(110, 27))
        self.rBextern.setObjectName(_fromUtf8("rBextern"))
        self.gridLayout.addWidget(self.rBextern, 3, 3, 1, 1)
        self.pBconfirm = QtGui.QPushButton(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBconfirm.sizePolicy().hasHeightForWidth())
        self.pBconfirm.setSizePolicy(sizePolicy)
        self.pBconfirm.setMinimumSize(QtCore.QSize(110, 27))
        self.pBconfirm.setObjectName(_fromUtf8("pBconfirm"))
        self.gridLayout.addWidget(self.pBconfirm, 4, 3, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.rBextern, QtCore.SIGNAL(_fromUtf8("pressed()")), self.rBstream.lower)
        QtCore.QObject.connect(self.rBstream, QtCore.SIGNAL(_fromUtf8("pressed()")), self.rBextern.lower)
        QtCore.QObject.connect(self.rBextern, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sBrate.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Config", None))
        self.label.setText(_translate("MainWindow", "Ch +", None))
        self.label_2.setText(_translate("MainWindow", "Rate(ms)", None))
        self.label_3.setText(_translate("MainWindow", "Ch -", None))
        self.label_4.setText(_translate("MainWindow", "Samples to read", None))
        self.label_5.setText(_translate("MainWindow", "Range", None))
        self.label_6.setText(_translate("MainWindow", "Mode", None))
        self.cBmode.setItemText(0, _translate("MainWindow", "Continuous", None))
        self.cBmode.setItemText(1, _translate("MainWindow", "No continuous", None))
        self.rBstream.setText(_translate("MainWindow", "Stream", None))
        self.rBextern.setText(_translate("MainWindow", "Extern", None))
        self.pBconfirm.setText(_translate("MainWindow", "Confirm", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

