# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easydaq/configurechart.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(244, 282)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(244, 282))
        MainWindow.setMaximumSize(QtCore.QSize(244, 282))
        self.formLayout = QtWidgets.QFormLayout(MainWindow)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cBtype = QtWidgets.QComboBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBtype.sizePolicy().hasHeightForWidth())
        self.cBtype.setSizePolicy(sizePolicy)
        self.cBtype.setMinimumSize(QtCore.QSize(110, 27))
        self.cBtype.setMaximumSize(QtCore.QSize(110, 27))
        self.cBtype.setObjectName("cBtype")
        self.cBtype.addItem("")
        self.cBtype.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cBtype)
        self.label_6 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 27))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cBmode = QtWidgets.QComboBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBmode.sizePolicy().hasHeightForWidth())
        self.cBmode.setSizePolicy(sizePolicy)
        self.cBmode.setMinimumSize(QtCore.QSize(100, 27))
        self.cBmode.setMaximumSize(QtCore.QSize(110, 27))
        self.cBmode.setObjectName("cBmode")
        self.cBmode.addItem("")
        self.cBmode.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cBmode)
        self.label = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 27))
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cBposchannel = QtWidgets.QComboBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBposchannel.sizePolicy().hasHeightForWidth())
        self.cBposchannel.setSizePolicy(sizePolicy)
        self.cBposchannel.setMinimumSize(QtCore.QSize(110, 27))
        self.cBposchannel.setObjectName("cBposchannel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cBposchannel)
        self.label_3 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 27))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cBnegchannel = QtWidgets.QComboBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBnegchannel.sizePolicy().hasHeightForWidth())
        self.cBnegchannel.setSizePolicy(sizePolicy)
        self.cBnegchannel.setMinimumSize(QtCore.QSize(110, 27))
        self.cBnegchannel.setObjectName("cBnegchannel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cBnegchannel)
        self.label_5 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 27))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cBrange = QtWidgets.QComboBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBrange.sizePolicy().hasHeightForWidth())
        self.cBrange.setSizePolicy(sizePolicy)
        self.cBrange.setMinimumSize(QtCore.QSize(110, 27))
        self.cBrange.setObjectName("cBrange")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cBrange)
        self.label_2 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 27))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sBrate = QtWidgets.QSpinBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBrate.sizePolicy().hasHeightForWidth())
        self.sBrate.setSizePolicy(sizePolicy)
        self.sBrate.setMinimumSize(QtCore.QSize(110, 27))
        self.sBrate.setMinimum(2)
        self.sBrate.setMaximum(65536)
        self.sBrate.setProperty("value", 10)
        self.sBrate.setObjectName("sBrate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sBrate)
        self.pBconfirm = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBconfirm.sizePolicy().hasHeightForWidth())
        self.pBconfirm.setSizePolicy(sizePolicy)
        self.pBconfirm.setMinimumSize(QtCore.QSize(110, 27))
        self.pBconfirm.setObjectName("pBconfirm")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pBconfirm)
        self.label_4 = QtWidgets.QLabel(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(110, 27))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sBsamples = QtWidgets.QSpinBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBsamples.sizePolicy().hasHeightForWidth())
        self.sBsamples.setSizePolicy(sizePolicy)
        self.sBsamples.setMinimumSize(QtCore.QSize(110, 27))
        self.sBsamples.setMaximum(999)
        self.sBsamples.setProperty("value", 200)
        self.sBsamples.setObjectName("sBsamples")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sBsamples)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Configuration"))
        self.label_7.setText(_translate("MainWindow", "Type"))
        self.cBtype.setItemText(0, _translate("MainWindow", "Stream"))
        self.cBtype.setItemText(1, _translate("MainWindow", "Extern"))
        self.label_6.setText(_translate("MainWindow", "Mode"))
        self.cBmode.setItemText(0, _translate("MainWindow", "Continuous"))
        self.cBmode.setItemText(1, _translate("MainWindow", "No continuous"))
        self.label.setText(_translate("MainWindow", "Ch +"))
        self.label_3.setText(_translate("MainWindow", "Ch -"))
        self.label_5.setText(_translate("MainWindow", "Range"))
        self.label_2.setText(_translate("MainWindow", "Rate(ms)"))
        self.pBconfirm.setText(_translate("MainWindow", "Confirm"))
        self.label_4.setText(_translate("MainWindow", "Samples to read"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

