# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easydaq/configwave.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(260, 220)
        mainWindow.setMinimumSize(QtCore.QSize(260, 220))
        mainWindow.setMaximumSize(QtCore.QSize(260, 225))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setHorizontalSpacing(10)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 27))
        self.label.setMaximumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cBmode = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBmode.sizePolicy().hasHeightForWidth())
        self.cBmode.setSizePolicy(sizePolicy)
        self.cBmode.setMinimumSize(QtCore.QSize(130, 27))
        self.cBmode.setMaximumSize(QtCore.QSize(120, 27))
        self.cBmode.setObjectName("cBmode")
        self.cBmode.addItem("")
        self.cBmode.addItem("")
        self.cBmode.addItem("")
        self.cBmode.addItem("")
        self.cBmode.addItem("")
        self.cBmode.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cBmode)
        self.verticalLayout.addLayout(self.formLayout_6)
        self.sWDC = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sWDC.sizePolicy().hasHeightForWidth())
        self.sWDC.setSizePolicy(sizePolicy)
        self.sWDC.setMinimumSize(QtCore.QSize(0, 30))
        self.sWDC.setObjectName("sWDC")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 242, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setHorizontalSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 27))
        self.label_3.setLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sBoffset = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBoffset.sizePolicy().hasHeightForWidth())
        self.sBoffset.setSizePolicy(sizePolicy)
        self.sBoffset.setMinimumSize(QtCore.QSize(130, 27))
        self.sBoffset.setDecimals(3)
        self.sBoffset.setMinimum(-4.0)
        self.sBoffset.setMaximum(4.0)
        self.sBoffset.setSingleStep(0.1)
        self.sBoffset.setProperty("value", 0.0)
        self.sBoffset.setObjectName("sBoffset")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBoffset)
        self.sWDC.addWidget(self.page)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.layoutWidget1 = QtWidgets.QWidget(self.page2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 242, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_8 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setHorizontalSpacing(10)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 27))
        self.label_5.setMaximumSize(QtCore.QSize(100, 27))
        self.label_5.setObjectName("label_5")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Bchoose = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bchoose.sizePolicy().hasHeightForWidth())
        self.Bchoose.setSizePolicy(sizePolicy)
        self.Bchoose.setMinimumSize(QtCore.QSize(130, 27))
        self.Bchoose.setMaximumSize(QtCore.QSize(120, 27))
        self.Bchoose.setObjectName("Bchoose")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Bchoose)
        self.sWDC.addWidget(self.page2)
        self.verticalLayout.addWidget(self.sWDC)
        self.sW2 = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sW2.sizePolicy().hasHeightForWidth())
        self.sW2.setSizePolicy(sizePolicy)
        self.sW2.setMinimumSize(QtCore.QSize(0, 65))
        self.sW2.setObjectName("sW2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.sW2.addWidget(self.page_3)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.lb_namefile = QtWidgets.QLabel(self.page_11)
        self.lb_namefile.setGeometry(QtCore.QRect(0, 10, 231, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_namefile.setFont(font)
        self.lb_namefile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_namefile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_namefile.setObjectName("lb_namefile")
        self.sW2.addWidget(self.page_11)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 242, 62))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 27))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sBamplitude = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBamplitude.sizePolicy().hasHeightForWidth())
        self.sBamplitude.setSizePolicy(sizePolicy)
        self.sBamplitude.setMinimumSize(QtCore.QSize(130, 27))
        self.sBamplitude.setDecimals(3)
        self.sBamplitude.setMaximum(8.0)
        self.sBamplitude.setSingleStep(0.1)
        self.sBamplitude.setProperty("value", 1.0)
        self.sBamplitude.setObjectName("sBamplitude")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBamplitude)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 27))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sBperiodms = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBperiodms.sizePolicy().hasHeightForWidth())
        self.sBperiodms.setSizePolicy(sizePolicy)
        self.sBperiodms.setMinimumSize(QtCore.QSize(130, 27))
        self.sBperiodms.setDecimals(3)
        self.sBperiodms.setMinimum(1.0)
        self.sBperiodms.setMaximum(65536.0)
        self.sBperiodms.setSingleStep(0.1)
        self.sBperiodms.setProperty("value", 200.0)
        self.sBperiodms.setObjectName("sBperiodms")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sBperiodms)
        self.sW2.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.sW2)
        self.sWtime = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sWtime.sizePolicy().hasHeightForWidth())
        self.sWtime.setSizePolicy(sizePolicy)
        self.sWtime.setMinimumSize(QtCore.QSize(0, 30))
        self.sWtime.setObjectName("sWtime")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.layoutWidget3 = QtWidgets.QWidget(self.page_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 242, 29))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 27))
        self.label_6.setLineWidth(0)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.sBtimeon = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBtimeon.sizePolicy().hasHeightForWidth())
        self.sBtimeon.setSizePolicy(sizePolicy)
        self.sBtimeon.setMinimumSize(QtCore.QSize(130, 27))
        self.sBtimeon.setDecimals(3)
        self.sBtimeon.setMinimum(0.0)
        self.sBtimeon.setMaximum(65536.0)
        self.sBtimeon.setSingleStep(1.0)
        self.sBtimeon.setProperty("value", 40.0)
        self.sBtimeon.setObjectName("sBtimeon")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBtimeon)
        self.sWtime.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 242, 29))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_7 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setHorizontalSpacing(10)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 27))
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.sBriseTime = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBriseTime.sizePolicy().hasHeightForWidth())
        self.sBriseTime.setSizePolicy(sizePolicy)
        self.sBriseTime.setMinimumSize(QtCore.QSize(130, 27))
        self.sBriseTime.setDecimals(3)
        self.sBriseTime.setMaximum(65536.0)
        self.sBriseTime.setProperty("value", 40.0)
        self.sBriseTime.setObjectName("sBriseTime")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sBriseTime)
        self.sWtime.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.sWtime.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.sWtime.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.sWtime.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.sWtime.addWidget(self.page_10)
        self.verticalLayout.addWidget(self.sWtime)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        spacerItem = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.Bsubmit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bsubmit.sizePolicy().hasHeightForWidth())
        self.Bsubmit.setSizePolicy(sizePolicy)
        self.Bsubmit.setMinimumSize(QtCore.QSize(130, 27))
        self.Bsubmit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Bsubmit.setObjectName("Bsubmit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Bsubmit)
        self.verticalLayout.addLayout(self.formLayout_5)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.sWDC.setCurrentIndex(0)
        self.sW2.setCurrentIndex(2)
        self.sWtime.setCurrentIndex(0)
        self.cBmode.currentIndexChanged['int'].connect(self.sWtime.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Wave Configuration"))
        self.label.setText(_translate("mainWindow", "Select mode"))
        self.cBmode.setItemText(0, _translate("mainWindow", "Square"))
        self.cBmode.setItemText(1, _translate("mainWindow", "Triangle"))
        self.cBmode.setItemText(2, _translate("mainWindow", "Sine"))
        self.cBmode.setItemText(3, _translate("mainWindow", "Sawtooth"))
        self.cBmode.setItemText(4, _translate("mainWindow", "Fixed potential"))
        self.cBmode.setItemText(5, _translate("mainWindow", "Import CSV"))
        self.label_3.setText(_translate("mainWindow", "DC Value (V)"))
        self.label_5.setText(_translate("mainWindow", "Select File"))
        self.Bchoose.setText(_translate("mainWindow", "Choose"))
        self.lb_namefile.setText(_translate("mainWindow", "no file selected"))
        self.label_4.setText(_translate("mainWindow", "Amplitude (V)"))
        self.label_2.setText(_translate("mainWindow", "Period (ms)"))
        self.label_6.setText(_translate("mainWindow", "Time On (ms)"))
        self.label_7.setText(_translate("mainWindow", "Rise Time (ms)"))
        self.Bsubmit.setText(_translate("mainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

