# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easydaq/configurechart.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(244, 282)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(244, 282))
        MainWindow.setMaximumSize(QtCore.QSize(244, 282))
        self.formLayout = QtGui.QFormLayout(MainWindow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cBtype = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBtype.sizePolicy().hasHeightForWidth())
        self.cBtype.setSizePolicy(sizePolicy)
        self.cBtype.setMinimumSize(QtCore.QSize(110, 27))
        self.cBtype.setMaximumSize(QtCore.QSize(110, 27))
        self.cBtype.setObjectName(_fromUtf8("cBtype"))
        self.cBtype.addItem(_fromUtf8(""))
        self.cBtype.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cBtype)
        self.label_6 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 27))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cBmode = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBmode.sizePolicy().hasHeightForWidth())
        self.cBmode.setSizePolicy(sizePolicy)
        self.cBmode.setMinimumSize(QtCore.QSize(100, 27))
        self.cBmode.setMaximumSize(QtCore.QSize(110, 27))
        self.cBmode.setObjectName(_fromUtf8("cBmode"))
        self.cBmode.addItem(_fromUtf8(""))
        self.cBmode.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cBmode)
        self.label = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 27))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.cBposchannel = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBposchannel.sizePolicy().hasHeightForWidth())
        self.cBposchannel.setSizePolicy(sizePolicy)
        self.cBposchannel.setMinimumSize(QtCore.QSize(110, 27))
        self.cBposchannel.setObjectName(_fromUtf8("cBposchannel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cBposchannel)
        self.label_3 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 27))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cBnegchannel = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBnegchannel.sizePolicy().hasHeightForWidth())
        self.cBnegchannel.setSizePolicy(sizePolicy)
        self.cBnegchannel.setMinimumSize(QtCore.QSize(110, 27))
        self.cBnegchannel.setObjectName(_fromUtf8("cBnegchannel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cBnegchannel)
        self.label_5 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cBrange = QtGui.QComboBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBrange.sizePolicy().hasHeightForWidth())
        self.cBrange.setSizePolicy(sizePolicy)
        self.cBrange.setMinimumSize(QtCore.QSize(110, 27))
        self.cBrange.setObjectName(_fromUtf8("cBrange"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cBrange)
        self.label_2 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 27))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sBrate = QtGui.QSpinBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBrate.sizePolicy().hasHeightForWidth())
        self.sBrate.setSizePolicy(sizePolicy)
        self.sBrate.setMinimumSize(QtCore.QSize(110, 27))
        self.sBrate.setMinimum(2)
        self.sBrate.setMaximum(65536)
        self.sBrate.setProperty("value", 10)
        self.sBrate.setObjectName(_fromUtf8("sBrate"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.sBrate)
        self.pBconfirm = QtGui.QPushButton(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBconfirm.sizePolicy().hasHeightForWidth())
        self.pBconfirm.setSizePolicy(sizePolicy)
        self.pBconfirm.setMinimumSize(QtCore.QSize(110, 27))
        self.pBconfirm.setObjectName(_fromUtf8("pBconfirm"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.pBconfirm)
        self.label_4 = QtGui.QLabel(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(110, 27))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sBsamples = QtGui.QSpinBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sBsamples.sizePolicy().hasHeightForWidth())
        self.sBsamples.setSizePolicy(sizePolicy)
        self.sBsamples.setMinimumSize(QtCore.QSize(110, 27))
        self.sBsamples.setMaximum(999)
        self.sBsamples.setProperty("value", 200)
        self.sBsamples.setObjectName(_fromUtf8("sBsamples"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.sBsamples)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Configuration", None))
        self.label_7.setText(_translate("MainWindow", "Type", None))
        self.cBtype.setItemText(0, _translate("MainWindow", "Stream", None))
        self.cBtype.setItemText(1, _translate("MainWindow", "Extern", None))
        self.label_6.setText(_translate("MainWindow", "Mode", None))
        self.cBmode.setItemText(0, _translate("MainWindow", "Continuous", None))
        self.cBmode.setItemText(1, _translate("MainWindow", "No continuous", None))
        self.label.setText(_translate("MainWindow", "Ch +", None))
        self.label_3.setText(_translate("MainWindow", "Ch -", None))
        self.label_5.setText(_translate("MainWindow", "Range", None))
        self.label_2.setText(_translate("MainWindow", "Rate(ms)", None))
        self.pBconfirm.setText(_translate("MainWindow", "Confirm", None))
        self.label_4.setText(_translate("MainWindow", "Samples to read", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

