# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easydaq/easydaq.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(892, 608)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 891, 552))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(3, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Bconfigure2 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure2.sizePolicy().hasHeightForWidth())
        self.Bconfigure2.setSizePolicy(sizePolicy)
        self.Bconfigure2.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure2.setObjectName(_fromUtf8("Bconfigure2"))
        self.gridLayout.addWidget(self.Bconfigure2, 3, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(70, 0))
        self.line_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_2.setStyleSheet(_fromUtf8("color: rgb(85, 170, 0);\n"
""))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 2, 1, 1)
        self.Bconfigure5 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure5.sizePolicy().hasHeightForWidth())
        self.Bconfigure5.setSizePolicy(sizePolicy)
        self.Bconfigure5.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure5.setObjectName(_fromUtf8("Bconfigure5"))
        self.gridLayout.addWidget(self.Bconfigure5, 9, 1, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(70, 0))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        self.line.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"font: 63 italic 16pt \"Ubuntu\";"))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 2, 1, 1)
        self.cBenable1 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable1.sizePolicy().hasHeightForWidth())
        self.cBenable1.setSizePolicy(sizePolicy)
        self.cBenable1.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable1.setObjectName(_fromUtf8("cBenable1"))
        self.gridLayout.addWidget(self.cBenable1, 1, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMinimumSize(QtCore.QSize(70, 0))
        self.line_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_4.setStyleSheet(_fromUtf8("color: rgb(227, 227, 0);"))
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setMidLineWidth(1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 7, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Bconfigure1 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure1.sizePolicy().hasHeightForWidth())
        self.Bconfigure1.setSizePolicy(sizePolicy)
        self.Bconfigure1.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure1.setObjectName(_fromUtf8("Bconfigure1"))
        self.gridLayout.addWidget(self.Bconfigure1, 1, 1, 1, 1)
        self.cBenable3 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable3.sizePolicy().hasHeightForWidth())
        self.cBenable3.setSizePolicy(sizePolicy)
        self.cBenable3.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable3.setObjectName(_fromUtf8("cBenable3"))
        self.gridLayout.addWidget(self.cBenable3, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.cBenable2 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable2.sizePolicy().hasHeightForWidth())
        self.cBenable2.setSizePolicy(sizePolicy)
        self.cBenable2.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable2.setObjectName(_fromUtf8("cBenable2"))
        self.gridLayout.addWidget(self.cBenable2, 3, 0, 1, 1)
        self.Bconfigure3 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure3.sizePolicy().hasHeightForWidth())
        self.Bconfigure3.setSizePolicy(sizePolicy)
        self.Bconfigure3.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure3.setObjectName(_fromUtf8("Bconfigure3"))
        self.gridLayout.addWidget(self.Bconfigure3, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.Bconfigure4 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure4.sizePolicy().hasHeightForWidth())
        self.Bconfigure4.setSizePolicy(sizePolicy)
        self.Bconfigure4.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure4.setObjectName(_fromUtf8("Bconfigure4"))
        self.gridLayout.addWidget(self.Bconfigure4, 7, 1, 1, 1)
        self.cBenable5 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable5.sizePolicy().hasHeightForWidth())
        self.cBenable5.setSizePolicy(sizePolicy)
        self.cBenable5.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable5.setObjectName(_fromUtf8("cBenable5"))
        self.gridLayout.addWidget(self.cBenable5, 9, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(70, 0))
        self.line_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 5, 2, 1, 1)
        self.cBenable4 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable4.sizePolicy().hasHeightForWidth())
        self.cBenable4.setSizePolicy(sizePolicy)
        self.cBenable4.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable4.setObjectName(_fromUtf8("cBenable4"))
        self.gridLayout.addWidget(self.cBenable4, 7, 0, 1, 1)
        self.Bplay = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bplay.sizePolicy().hasHeightForWidth())
        self.Bplay.setSizePolicy(sizePolicy)
        self.Bplay.setMinimumSize(QtCore.QSize(100, 27))
        self.Bplay.setCheckable(True)
        self.Bplay.setAutoRepeat(False)
        self.Bplay.setAutoDefault(False)
        self.Bplay.setObjectName(_fromUtf8("Bplay"))
        self.gridLayout.addWidget(self.Bplay, 11, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 1, 1, 1)
        self.Bstop = QtGui.QPushButton(self.layoutWidget)
        self.Bstop.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bstop.sizePolicy().hasHeightForWidth())
        self.Bstop.setSizePolicy(sizePolicy)
        self.Bstop.setMinimumSize(QtCore.QSize(100, 27))
        self.Bstop.setObjectName(_fromUtf8("Bstop"))
        self.gridLayout.addWidget(self.Bstop, 12, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.plotWidget = MPL_Widget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(550, 532))
        self.plotWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.horizontalLayout.addWidget(self.plotWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 25))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConfigure = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.actionConfigure.setIcon(icon)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.toolBar.addAction(self.actionConfigure)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop.setEnabled)
        QtCore.QObject.connect(self.Bstop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bplay.toggle)
        QtCore.QObject.connect(self.Bstop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bstop.setEnabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cBenable1.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cBenable2.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cBenable3.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cBenable4.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cBenable5.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bconfigure1.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bconfigure2.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bconfigure3.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bconfigure4.setDisabled)
        QtCore.QObject.connect(self.Bplay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Bconfigure5.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Easydaq", None))
        self.Bconfigure2.setText(_translate("MainWindow", "Configure", None))
        self.Bconfigure5.setText(_translate("MainWindow", "Configure", None))
        self.cBenable1.setText(_translate("MainWindow", "Enable", None))
        self.label_5.setText(_translate("MainWindow", "Waveform", None))
        self.label.setText(_translate("MainWindow", "Experiment 1", None))
        self.Bconfigure1.setText(_translate("MainWindow", "Configure", None))
        self.cBenable3.setText(_translate("MainWindow", "Enable", None))
        self.label_2.setText(_translate("MainWindow", "Experiment 2", None))
        self.cBenable2.setText(_translate("MainWindow", "Enable", None))
        self.Bconfigure3.setText(_translate("MainWindow", "Configure", None))
        self.label_4.setText(_translate("MainWindow", "Experiment 4", None))
        self.Bconfigure4.setText(_translate("MainWindow", "Configure", None))
        self.cBenable5.setText(_translate("MainWindow", "Enable", None))
        self.label_3.setText(_translate("MainWindow", "Experiment 3", None))
        self.cBenable4.setText(_translate("MainWindow", "Enable", None))
        self.Bplay.setText(_translate("MainWindow", "Play", None))
        self.Bstop.setText(_translate("MainWindow", "Stop", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionConfigure.setText(_translate("MainWindow", "Configure", None))

from widgets import MPL_Widget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

