# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easydaq/easydaq.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(806, 651)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.cBenable1 = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable1.sizePolicy().hasHeightForWidth())
        self.cBenable1.setSizePolicy(sizePolicy)
        self.cBenable1.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable1.setObjectName(_fromUtf8("cBenable1"))
        self.verticalLayout.addWidget(self.cBenable1)
        self.Bconfigure1 = QtGui.QPushButton(self.centralwidget)
        self.Bconfigure1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure1.sizePolicy().hasHeightForWidth())
        self.Bconfigure1.setSizePolicy(sizePolicy)
        self.Bconfigure1.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure1.setObjectName(_fromUtf8("Bconfigure1"))
        self.verticalLayout.addWidget(self.Bconfigure1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(85, 170, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.cBenable2 = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable2.sizePolicy().hasHeightForWidth())
        self.cBenable2.setSizePolicy(sizePolicy)
        self.cBenable2.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable2.setObjectName(_fromUtf8("cBenable2"))
        self.verticalLayout.addWidget(self.cBenable2)
        self.Bconfigure2 = QtGui.QPushButton(self.centralwidget)
        self.Bconfigure2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure2.sizePolicy().hasHeightForWidth())
        self.Bconfigure2.setSizePolicy(sizePolicy)
        self.Bconfigure2.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure2.setObjectName(_fromUtf8("Bconfigure2"))
        self.verticalLayout.addWidget(self.Bconfigure2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.cBenable3 = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable3.sizePolicy().hasHeightForWidth())
        self.cBenable3.setSizePolicy(sizePolicy)
        self.cBenable3.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable3.setObjectName(_fromUtf8("cBenable3"))
        self.verticalLayout.addWidget(self.cBenable3)
        self.Bconfigure3 = QtGui.QPushButton(self.centralwidget)
        self.Bconfigure3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure3.sizePolicy().hasHeightForWidth())
        self.Bconfigure3.setSizePolicy(sizePolicy)
        self.Bconfigure3.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure3.setObjectName(_fromUtf8("Bconfigure3"))
        self.verticalLayout.addWidget(self.Bconfigure3)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.cBenable4 = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBenable4.sizePolicy().hasHeightForWidth())
        self.cBenable4.setSizePolicy(sizePolicy)
        self.cBenable4.setMinimumSize(QtCore.QSize(100, 27))
        self.cBenable4.setObjectName(_fromUtf8("cBenable4"))
        self.verticalLayout.addWidget(self.cBenable4)
        self.Bconfigure4 = QtGui.QPushButton(self.centralwidget)
        self.Bconfigure4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bconfigure4.sizePolicy().hasHeightForWidth())
        self.Bconfigure4.setSizePolicy(sizePolicy)
        self.Bconfigure4.setMinimumSize(QtCore.QSize(100, 27))
        self.Bconfigure4.setObjectName(_fromUtf8("Bconfigure4"))
        self.verticalLayout.addWidget(self.Bconfigure4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plotWidget = MPL_Widget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(550, 532))
        self.plotWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.verticalLayout_2.addWidget(self.plotWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cBosc = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBosc.sizePolicy().hasHeightForWidth())
        self.cBosc.setSizePolicy(sizePolicy)
        self.cBosc.setMinimumSize(QtCore.QSize(130, 22))
        self.cBosc.setMaximumSize(QtCore.QSize(130, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cBosc.setFont(font)
        self.cBosc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cBosc.setAutoFillBackground(False)
        self.cBosc.setObjectName(_fromUtf8("cBosc"))
        self.horizontalLayout_2.addWidget(self.cBosc)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(28, 28))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 25))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionConfigure = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigure.setIcon(icon)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon1)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon2)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionCSV = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/CSV.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCSV.setIcon(icon3)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.toolBar.addAction(self.actionConfigure)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionCSV)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.cBenable1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bconfigure1.setEnabled)
        QtCore.QObject.connect(self.cBenable2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bconfigure2.setEnabled)
        QtCore.QObject.connect(self.cBenable3, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bconfigure3.setEnabled)
        QtCore.QObject.connect(self.cBenable4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Bconfigure4.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Easydaq", None))
        self.label.setText(_translate("MainWindow", "Experiment 1", None))
        self.cBenable1.setText(_translate("MainWindow", "Enable", None))
        self.Bconfigure1.setText(_translate("MainWindow", "Configure", None))
        self.label_2.setText(_translate("MainWindow", "Experiment 2", None))
        self.cBenable2.setText(_translate("MainWindow", "Enable", None))
        self.Bconfigure2.setText(_translate("MainWindow", "Configure", None))
        self.label_3.setText(_translate("MainWindow", "Experiment 3", None))
        self.cBenable3.setText(_translate("MainWindow", "Enable", None))
        self.Bconfigure3.setText(_translate("MainWindow", "Configure", None))
        self.label_5.setText(_translate("MainWindow", "Waveform", None))
        self.cBenable4.setText(_translate("MainWindow", "Enable", None))
        self.Bconfigure4.setText(_translate("MainWindow", "Configure", None))
        self.cBosc.setText(_translate("MainWindow", "Oscilloscope", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionConfigure.setText(_translate("MainWindow", "Configure", None))
        self.actionPlay.setText(_translate("MainWindow", "play", None))
        self.actionStop.setText(_translate("MainWindow", "stop", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))

from .widgets import MPL_Widget
from . import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

